//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA47_Team12_StationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogueInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogueInventory()
        {
            this.Disbursements = new HashSet<Disbursement>();
            this.Outstandings = new HashSet<Outstanding>();
            this.POes = new HashSet<PO>();
            this.RequestDetails = new HashSet<RequestDetail>();
            this.VoucherDetails = new HashSet<VoucherDetail>();
            this.StockCards = new HashSet<StockCard>();
        }
    
        public string ItemID { get; set; }
        public Nullable<int> CatID { get; set; }
        public string Item_Description { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<int> ReorderQty { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<int> ActualQty { get; set; }
        public Nullable<int> Priority1 { get; set; }
        public Nullable<int> Priority2 { get; set; }
        public Nullable<int> Priority3 { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Supplier Supplier1 { get; set; }
        public virtual Supplier Supplier2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disbursement> Disbursements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outstanding> Outstandings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO> POes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestDetail> RequestDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoucherDetail> VoucherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockCard> StockCards { get; set; }
    }
}
