//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA47_Team12_StationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outstanding
    {
        public int OutstandingID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Status { get; set; }
    
        public virtual CatalogueInventory CatalogueInventory { get; set; }
        public virtual Department Department { get; set; }
    }
}
