//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA47_Team12_StationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherDetail
    {
        public int AdjustmentID { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> AdjustedQty { get; set; }
        public Nullable<decimal> AdjustedAmt { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Remarks { get; set; }
    
        public virtual CatalogueInventory CatalogueInventory { get; set; }
        public virtual Voucher Voucher { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
